name: Registration Library CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest requests
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length 120 --count --statistics .
    - name: Check code format with black
      run: |
        black --check --diff --color .
    - name: Run tests
      run: |
        pytest
